name = "Referenceables"
uuid = "42d2dcc6-99eb-4e98-b66c-637b7d73030e"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com>"]
version = "0.1.2"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"

[compat]
Adapt = "2, 3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
